baseURL = "https://reef-pi.github.io"
languageCode = "en-us"
title = "reef-pi - A Rasoberry Pi based opensource reef tank controller"
theme = "hugo-sustain"
publishDir = "../reef-pi.github.io"

[params]
Author = "Ranjib Dey"
Description = "reef-pi - A Rasoberry Pi based opensource reef tank controller"

[params.social]
  Github    = "reef-pi"
  Email     = "info@reef-pi.com"
  Twitter   = "reef_pi"
