baseURL = "https://reef-pi.github.io/"
languageCode = "en-us"
title = "reef-pi - A Rasoberry Pi based opensource reef tank controller"
theme = "hugo-sustain"
publishDir = "../reef-pi.github.io"
googleAnalytics = "UA-102968086-1"

[params]
Author = "Ranjib Dey"
Description = "reef-pi - A Rasoberry Pi based opensource reef tank controller"

[params.social]
  Github    = "reef-pi"
  Email     = "info@reef-pi.com"
  Twitter   = "reef_pi"

[[menu.main]]
  name = "general guides"
  identifier = "general-guides"
  weight = 100
  url = "/general-guides/"

[[menu.main]]
  name = "build guides"
  identifier = "build-guides"
  weight = 200
  url = "/build-guides/"

[[menu.main]]
  name = "blogs"
  identifier = "blogs"
  weight = 300
  url = "/blogs/"

